### ISSUE TITLE
Add parameters for colors

### ISSUE THREAD

**Issue by AaronHolbrook** [trepmal/generate-image#1]
Cool workflow @trepmal !

Any desire to add some customization options for colors?

**Comment by trepmal** [comment]
Definitely something I've considered. I want to make sure that it's as easy as possible, and completely optional (this workflow should be a no brainer to use).

Ideas on what the color options might look like in the command? Maybe

```
img 400x300 bg-color text-color
```

I hesitate to go with flags, but if there's any likelihood of adding additional options (label, image type, etc), it might be clearer to have that kind of inline labeling.

**Comment by AaronHolbrook** [comment]
Yea I would do something like `img 100x100 bg-color text-color`

Keep it simple, but allow a bit of customization.

**Comment by trepmal** [comment]
added in 96c4201b4ede061b1fd39f7436b4d34b1ca60237
