### ISSUE TITLE
Doesn't seem to work (even with convert command available)

### ISSUE THREAD

**Issue by AaronHolbrook** [trepmal/generate-image#3]
It says successful, but no image shows up on the desktop

**Comment by AaronHolbrook** [comment]
Ah, that's because you hardcoded the path of `convert` - whereas I have it installed in a different location: ![](http://d.pr/i/acUu/mO041VhE+)

**Comment by trepmal** [comment]
I should do some checking though...

**Comment by trepmal** [comment]
05f54fbb469f7dbce1b6ea6c205631ace0da9ab3 tries to be nicer about where it looks for `convert`
